const FETCH_USER = 'FETCH_USER';
const GET_USER = 'GET_USER';
const GET_TASKS = 'GET_TASKS';
const START_TASK = 'START_TASK';
const STOP_TASK = 'STOP_TASK';
const SAVE_TASK = 'SAVE_TASK';
const SET_MODAL_STATE = 'SET_MODAL_STATE';
const UPDATE_TASK = 'UPDATE_TASK';
const GET_TIME_LOG_BY_TASK = 'GET_TIME_LOG_BY_TASK';
const CLOSE_OPEN_TASK = 'CLOSE_OPEN_TASK';
const SET_LOG_VIEW_STATE = 'SET_LOG_VIEW_STATE';
const GET_TASK_TIME = 'GET_TASK_TIME';

export {
    FETCH_USER,
    GET_USER,
    GET_TASKS,
    START_TASK,
    STOP_TASK,
    SAVE_TASK,
    UPDATE_TASK,
    SET_MODAL_STATE,
    GET_TIME_LOG_BY_TASK,
    CLOSE_OPEN_TASK,
    SET_LOG_VIEW_STATE,
    GET_TASK_TIME
}